---
# defaults file for wordpress
wordpress_packages:
  - httpd
  - mysql
  - python-pip
  - gcc
  - mysql-devel
  - php
  - php-mysqlnd
  - php-mbstring
wordpress_database_host: 'rds_host' #replace with RDS endpoint
wordpress_database: 'wordpress'
wordpress_user: 'admin'
wordpress_password: 'rds_password' 
wordpress_configuration: '/var/www/html/wp-config.php'
